Added endpoint to get all subjects in database
Edge-Academy-UFAL/student-manager pull request #23
Opened 2024-05-09 16:48 UTC by filipeferreirasoriano

![Screenshot from 2024-05-09 13-42-34](https://github.com/Edge-Academy-UFAL/student-manager/assets/130411621/e681d28c-249a-4e23-afc2-a0f8775ce406)
O endpoint retorna uma lista do SubjectResponseDTO, que contem o codigo, o nome e a carga horária da disciplina

2024-05-09 17:11 UTC, ricardovinicius approved these changes
Bom e funcional 
![Salute-Memoji](https://github.com/Edge-Academy-UFAL/student-manager/assets/108153768/cba2915e-0954-4877-b37b-64c8d1aca82d)

2024-05-10 12:52 UTC, daviromao requested changes

2024-05-10 12:52 UTC, daviromao commented on src/main/java/com/academy/edge/studentmanager/controllers/SubjectController.java
> +    @GetMapping
Permitir que apenas pessoas autenticadas consigam acessar :)

2024-05-10 12:52 UTC, daviromao commented on src/main/java/com/academy/edge/studentmanager/controllers/SubjectController.java
> +    }
Imagino que a criação de uma matéria não deva ser responsabilidade de um usuário e sim do próprio sistema. Podemos apagar esse endpoint.

2024-05-10 12:52 UTC, daviromao commented on src/main/java/com/academy/edge/studentmanager/dtos/SubjectCreateDTO.java
> +}
Remover DTO já que todas as matérias são populadas automaticamente pelo sistema.

2024-05-10 12:52 UTC, daviromao commented on src/main/java/com/academy/edge/studentmanager/services/SubjectService.java
> +    SubjectResponseDTO insertSubject(SubjectCreateDTO subjectCreateDTO);
Remover inserção

2024-05-10 12:52 UTC, daviromao commented on src/main/java/com/academy/edge/studentmanager/services/impl/SubjectServiceImpl.java
> +    }
remover inserção

2024-05-10 13:00 UTC, filipeferreirasoriano commented on src/main/java/com/academy/edge/studentmanager/controllers/SubjectController.java
> +    }
A task de inserir as disciplinas no Jira foi atualizada e pede para criar endpoints para adicionar, remover e atualizar disciplinas. Devo ter dado commit na branch errada, era para ter sido na insert-all-subjects.

2024-05-13 12:46 UTC, merged